# Aliases
alias ls='ls --color=auto'
alias s='sudo'
alias uppkgs='s pacman -Syu && yay -Syu'
alias copy='xclip -selection clipboard -in'
alias paste='xclip -selection clipboard -out'
alias tmuxcp='tmux show-buffer | copy'
alias mp3dl='youtube-dl -x --ignore-errors --download-archive downloaded.txt --audio-quality 0 --audio-format mp3 -o "%(title)s.%(ext)s"'
alias syncdirs='rsync -avzP --delete'
alias mountandroid='simple-mtpfs ~/mnt'
alias umountandroid='fusermount -u ~/mnt'
alias cpw='lpass show --password --clip'
alias trashls='gio list trash://'
alias trashempty='gio trash --empty'
alias bkupkgs='pacman -Qqe | grep -v "$(pacman -Qqm)" > ~/.dotfiles-local/backup/pacman.lst && pacman -Qqm > ~/.dotfiles-local/backup/aur.lst'
alias bkupdots='bkupkgs; g -C ~/.dotfiles commit -am "update"; g -C ~/.dotfiles push; \
    g -C ~/.dotfiles-local commit -am "update"; g -C ~/.dotfiles-local push'
