#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

### BEGIN Shutdown option ###

menuentry "System shutdown" {
	echo "System shutting down..."
	halt
}

### END Shutdown option ###

### BEGIN Restart option ###

menuentry "System restart" {
	echo "System rebooting..."
	reboot
}

### END Restart option ###
